site_name: Documentation
site_description: Tài liệu dự án
site_author: Vũ Văn Nghĩa

theme:
  name: material
  features:
    - navigation.footer
    - navigation.keyboard

plugins:
  - search:
      lang: vi
  - mkdocs-nav-weight

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
