graph TB
    %% Định nghĩa màu sắc (Styles)
    classDef client fill:#000,stroke:#fff,stroke-width:2px,color:#fff;
    classDef gateway  fill:#3776ab,stroke:#fff,stroke-width:1px,color:#fff;
    classDef nestjs fill:#e0234e,stroke:#fff,stroke-width:1px,color:#fff;
    classDef python fill:#f96,stroke:#333,stroke-width:2px;
    classDef database  fill:#3776ab,stroke:#fff,stroke-width:1px,color:#fff;

    %% Nodes
    Client["Next.js Client"]:::client

    %% Gateway Layer
    Kong["Kong API Gateway"]:::gateway

    %% NestJS Ecosystem
    Payment["Payment Service"]:::nestjs
    Conv["Conversation Service"]:::nestjs
    Auth["Auth Service"]:::nestjs
    Persona["Persona Service"]:::nestjs
    Supa[("Supabase")]:::database
    Auth --- Supa

    %% Python Ecosystem
    Chatbot["Chatbot (LangGraph) + Voice (LiveKit)"]:::python
    Doc["Document (Docling)"]:::python

    %% Others
    Setting["Setting Service"]:::nestjs
    Neon[("Neon API")]:::database
    Setting --- Neon

    %% Connections
    Client --> Kong




    %% Logic Flow
    Conv <--> Chatbot
    Chatbot --> Doc
    Chatbot --> Persona




    Kong --> Auth
    Kong --> Setting
    Kong --> Payment
    Kong --> Conv
    Kong --> Persona
    Kong --> Chatbot
    Kong --> Doc
