name: Build Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv add mkdocs mkdocs-material

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force
